# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bellman_ford <- function(edges, vertex_source) {
    invisible(.Call('_M2pathfinding_bellman_ford', PACKAGE = 'M2pathfinding', edges, vertex_source))
}

find_distance_min <- function(distance, visited, n) {
    .Call('_M2pathfinding_find_distance_min', PACKAGE = 'M2pathfinding', distance, visited, n)
}

short_path <- function(parent, j) {
    invisible(.Call('_M2pathfinding_short_path', PACKAGE = 'M2pathfinding', parent, j))
}

path <- function(dist, n, parent) {
    invisible(.Call('_M2pathfinding_path', PACKAGE = 'M2pathfinding', dist, n, parent))
}

dijkstra_cpp <- function(edges) {
    invisible(.Call('_M2pathfinding_dijkstra_cpp', PACKAGE = 'M2pathfinding', edges))
}

